Repository tinylunark/lunark-android, pull requests merged in 2024-01, with the labels that each got.

#19 Feature/3.10/property detail
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/lunark/adapters/PropertyListAdapter.java
  app/src/main/java/com/example/lunark/adapters/ReviewListAdapter.java
  app/src/main/java/com/example/lunark/fragments/PropertiesFragment.java
  app/src/main/java/com/example/lunark/fragments/PropertyDetailFragment.java
  app/src/main/java/com/example/lunark/models/Address.java
  app/src/main/java/com/example/lunark/models/Amenity.java
  app/src/main/java/com/example/lunark/models/AvailabilityEntry.java
  app/src/main/java/com/example/lunark/models/Property.java
  app/src/main/java/com/example/lunark/models/PropertyImage.java
  app/src/main/java/com/example/lunark/models/Review.java
  app/src/main/java/com/example/lunark/repositories/PropertyRepository.java
  app/src/main/java/com/example/lunark/services/PropertyService.java
  app/src/main/java/com/example/lunark/util/ClientUtils.java
  app/src/main/java/com/example/lunark/util/JsonDateDeserializer.java
  app/src/main/java/com/example/lunark/util/PropertyListMockup.java
  app/src/main/java/com/example/lunark/viewmodels/PropertiesViewModel.java
  app/src/main/java/com/example/lunark/viewmodels/PropertyDetailViewModel.java
  app/src/main/res/drawable-night/ic_star.xml
  app/src/main/res/drawable/ic_star.xml
  app/src/main/res/layout/fragment_properties.xml
  app/src/main/res/layout/fragment_property_detail.xml
  app/src/main/res/layout/property_card.xml
  app/src/main/res/layout/review_card.xml
  app/src/main/res/values/strings.xml
Labels: feature

#23 Duplicate getRole method
  app/src/main/java/com/example/lunark/models/Login.java
Labels: hotfix

#24 3.25 Favorite properties
  app/build.gradle.kts
  app/src/main/java/com/example/lunark/ApplicationComponent.java
  app/src/main/java/com/example/lunark/LunarkApplication.java
  app/src/main/java/com/example/lunark/clients/AccountService.java
  app/src/main/java/com/example/lunark/datasources/AccountNetworkDataSource.java
  app/src/main/java/com/example/lunark/datasources/AccountRepository.java
  app/src/main/java/com/example/lunark/fragments/FavoritePropertiesFragment.java
  app/src/main/java/com/example/lunark/fragments/PropertyDetailFragment.java
  app/src/main/java/com/example/lunark/util/ClientUtils.java
  app/src/main/res/layout/fragment_favorite_properties.xml
  app/src/main/res/layout/fragment_property_detail.xml
  app/src/main/res/menu/nav_menu.xml
  app/src/main/res/navigation/base_navigation.xml
  app/src/main/res/values/strings.xml
Labels: feature

#26 3.24 Reports
  app/build.gradle.kts
  app/src/main/java/com/example/lunark/ApplicationComponent.java
  app/src/main/java/com/example/lunark/adapters/PropertySpinnerAdapter.java
  app/src/main/java/com/example/lunark/adapters/ReportsPagerAdapter.java
  app/src/main/java/com/example/lunark/clients/ReportService.java
  app/src/main/java/com/example/lunark/datasources/ReportNetworkDataSource.java
  app/src/main/java/com/example/lunark/fragments/GeneralReportFragment.java
  app/src/main/java/com/example/lunark/fragments/PropertyReportFragment.java
  app/src/main/java/com/example/lunark/fragments/ReportsFragment.java
  app/src/main/java/com/example/lunark/models/DailyReport.java
  app/src/main/java/com/example/lunark/models/GeneralReport.java
  app/src/main/java/com/example/lunark/models/MonthlyReport.java
  app/src/main/java/com/example/lunark/models/PropertyReport.java
  app/src/main/java/com/example/lunark/repositories/PropertyRepository.java
  app/src/main/java/com/example/lunark/repositories/ReportRepository.java
  app/src/main/java/com/example/lunark/services/PropertyService.java
  app/src/main/java/com/example/lunark/viewmodels/PropertyDetailViewModel.java
  app/src/main/res/layout/fragment_general_report.xml
  app/src/main/res/layout/fragment_property_report.xml
  app/src/main/res/layout/fragment_reports.xml
  app/src/main/res/menu/host_nav_menu.xml
  app/src/main/res/navigation/base_navigation.xml
  app/src/main/res/values/strings.xml
  settings.gradle.kts
Labels: feature

#29 #3.21.1 Toggle notifications
  app/build.gradle.kts
  app/src/main/java/com/example/lunark/ApplicationComponent.java
  app/src/main/java/com/example/lunark/clients/AccountService.java
  app/src/main/java/com/example/lunark/dtos/AccountDto.java
  app/src/main/java/com/example/lunark/dtos/NotificationSettingsDto.java
  app/src/main/java/com/example/lunark/fragments/GuestSettingsFragment.java
  app/src/main/java/com/example/lunark/fragments/HostSettingsFragment.java
  app/src/main/java/com/example/lunark/models/GuestNotificationSettings.java
  app/src/main/java/com/example/lunark/models/HostNotificationSettings.java
  app/src/main/java/com/example/lunark/util/RestPreferenceDataStore.java
  app/src/main/res/drawable/baseline_favorite_24.xml
  app/src/main/res/drawable/baseline_settings_24.xml
  app/src/main/res/menu/admin_nav_menu.xml
  app/src/main/res/menu/host_nav_menu.xml
  app/src/main/res/menu/nav_menu.xml
  app/src/main/res/navigation/base_navigation.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/guest_preferences.xml
  app/src/main/res/xml/host_preferences.xml
Labels: feature

#31 3.9 Property search and filter
  app/src/main/java/com/example/lunark/ApplicationComponent.java
  app/src/main/java/com/example/lunark/fragments/FiltersDialogFragment.java
  app/src/main/java/com/example/lunark/fragments/PropertiesFragment.java
  app/src/main/java/com/example/lunark/repositories/PropertyRepository.java
  app/src/main/java/com/example/lunark/util/DoubleToStringConverter.java
  app/src/main/java/com/example/lunark/util/IntegerToStringConverter.java
  app/src/main/java/com/example/lunark/util/LocalDateToStringConverter.java
  app/src/main/java/com/example/lunark/viewmodels/PropertiesViewModel.java
  app/src/main/java/com/example/lunark/viewmodels/PropertySearchState.java
  app/src/main/res/layout/fragment_filters_dialog.xml
  app/src/main/res/layout/fragment_properties.xml
  app/src/main/res/values/strings.xml
Labels: feature

#32 Host reviews
  app/build.gradle.kts
  app/src/main/java/com/example/lunark/ApplicationComponent.java
  app/src/main/java/com/example/lunark/HomeActivity.java
  app/src/main/java/com/example/lunark/datasources/AccountNetworkDataSource.java
  app/src/main/java/com/example/lunark/datasources/AccountRepository.java
  app/src/main/java/com/example/lunark/datasources/ReviewNetworkDataSource.java
  app/src/main/java/com/example/lunark/dtos/AccountDto.java
  app/src/main/java/com/example/lunark/fragments/HostPageFragment.java
  app/src/main/java/com/example/lunark/fragments/PropertyDetailFragment.java
  app/src/main/java/com/example/lunark/models/Host.java
  app/src/main/java/com/example/lunark/models/HostReviewEligibility.java
  app/src/main/java/com/example/lunark/models/Property.java
  app/src/main/java/com/example/lunark/repositories/ReviewRepository.java
  app/src/main/java/com/example/lunark/services/ReviewService.java
  app/src/main/java/com/example/lunark/viewmodels/HostViewModel.java
  app/src/main/java/com/example/lunark/viewmodels/ReviewViewModel.java
  app/src/main/res/drawable-night/ic_account.xml
  app/src/main/res/drawable/ic_account_on_primary_container.xml
  app/src/main/res/drawable/ic_report.xml
  app/src/main/res/drawable/ic_star_on_primary_container.xml
  app/src/main/res/drawable/ic_write_review.xml
  app/src/main/res/layout/fragment_host_page.xml
  app/src/main/res/layout/fragment_property_detail.xml
  app/src/main/res/navigation/base_navigation.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: feature

#34 3.11 Booking request
  app/src/main/java/com/example/lunark/ApplicationComponent.java
  app/src/main/java/com/example/lunark/HomeActivity.java
  app/src/main/java/com/example/lunark/LunarkApplication.java
  app/src/main/java/com/example/lunark/clients/ReservationService.java
  app/src/main/java/com/example/lunark/dtos/CreateReservationDto.java
  app/src/main/java/com/example/lunark/fragments/BookingRequestFragment.java
  app/src/main/java/com/example/lunark/fragments/PropertyDetailFragment.java
  app/src/main/java/com/example/lunark/models/AvailabilityEntry.java
  app/src/main/java/com/example/lunark/repositories/ReservationRepository.java
  app/src/main/java/com/example/lunark/validators/BookingDateValidator.java
  app/src/main/java/com/example/lunark/viewmodels/BookingRequestViewModel.java
  app/src/main/res/layout/fragment_booking_request.xml
  app/src/main/res/layout/fragment_property_detail.xml
  app/src/main/res/navigation/base_navigation.xml
Labels: feature

#38 3.13 Request search and filters
  app/src/main/java/com/example/lunark/clients/ReservationService.java
  app/src/main/java/com/example/lunark/fragments/AllReservationsFragment.java
  app/src/main/java/com/example/lunark/fragments/GuestCancelReservationFragment.java
  app/src/main/java/com/example/lunark/fragments/PendingReservationsFragment.java
  app/src/main/java/com/example/lunark/fragments/PropertiesFragment.java
  app/src/main/java/com/example/lunark/models/ReservationStatus.java
  app/src/main/java/com/example/lunark/repositories/ReservationRepository.java
  app/src/main/java/com/example/lunark/viewmodels/ReservationsViewModel.java
  app/src/main/res/layout/fragment_guest_cancel_reservation.xml
  app/src/main/res/layout/fragment_pending_reservation.xml
  app/src/main/res/values/strings.xml
Labels: feature

#39 Guest reports
  app/src/main/java/com/example/lunark/adapters/ReservationsListAdapterBase.java
  app/src/main/java/com/example/lunark/fragments/AccountReportFragment.java
  app/src/main/java/com/example/lunark/fragments/AllReservationsFragment.java
  app/src/main/java/com/example/lunark/models/Reservation.java
  app/src/main/java/com/example/lunark/repositories/AccountReportRepository.java
  app/src/main/res/layout/fragment_account_report.xml
  app/src/main/res/layout/reservation_card_base.xml
  app/src/main/res/values/strings.xml
Labels: feature

#40 3.14 Booking request deletion
  app/src/main/java/com/example/lunark/adapters/ReservationsCancelListAdapter.java
  app/src/main/java/com/example/lunark/clients/ReservationService.java
  app/src/main/java/com/example/lunark/fragments/GuestCancelReservationFragment.java
  app/src/main/java/com/example/lunark/repositories/ReservationRepository.java
  app/src/main/java/com/example/lunark/viewmodels/ReservationsViewModel.java
  app/src/main/res/layout/reservation_card_cancel.xml
Labels: feature

#42 Search optimization and reservation list refactoring
  app/src/main/java/com/example/lunark/adapters/PropertyListAdapter.java
  app/src/main/java/com/example/lunark/adapters/ReservationsCancelListAdapter.java
  app/src/main/java/com/example/lunark/adapters/ReservationsListAdapterBase.java
  app/src/main/java/com/example/lunark/fragments/AllReservationsFragment.java
  app/src/main/java/com/example/lunark/fragments/GuestCancelReservationFragment.java
  app/src/main/java/com/example/lunark/fragments/PropertiesFragment.java
  app/src/main/java/com/example/lunark/viewmodels/PropertiesViewModel.java
  app/src/main/java/com/example/lunark/viewmodels/ReservationsViewModel.java
  app/src/main/res/layout/reservation_card_base.xml
  app/src/main/res/layout/reservation_card_cancel.xml
Labels: refactor, fix

#44 Sort properties on device shake
  app/build.gradle.kts
  app/src/main/java/com/example/lunark/fragments/PropertiesFragment.java
  app/src/main/java/com/example/lunark/models/SortOrder.java
  app/src/main/java/com/example/lunark/viewmodels/PropertiesViewModel.java
  app/src/main/res/values/strings.xml
Labels: feature
